# -*- mode: ruby -*-
# vi: set ft=ruby :

require './hack/kubeadm-playground.rb'

machines = Playground.machines

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  machines.each do |machineSpec|
    config.vm.define "#{machineSpec.name}" do |machine|
      machine.vm.box = "#{machineSpec.box}"
      machine.vm.hostname = "#{machineSpec.hostname}"
      machine.vm.network :private_network,
        :ip => "#{machineSpec.ip}",
        :libvirt__forward_mode => "none",
        :libvirt__network_name => "kubernetes",
        :libvirt__netmask => "255.255.255.0",
        :virtualbox__intnet => "kubenetwork"
      machine.vm.provider "virtualbox" do |v|
        v.name = "#{machineSpec.name}"
  	    v.memory = "#{machineSpec.memory}"
        v.cpus = "#{machineSpec.cpus}"
        v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
        v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
      end
      
      # fallback_bootstrap is invoke only if ansible is not installed
      config.vm.provision "fallback_bootstrap", type:"shell", run: "never", inline: <<-SHELL
        #!/bin/sh
        set -ex
        
        apt-get update && apt-get install -y apt-transport-https
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
        echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
        apt-get update && apt-get install -y \
          docker.io=1.13.1-0ubuntu6 \
          kubelet=1.9.7-00 \
          kubectl=1.9.7-00 \
          kubeadm=1.9.7-00
        
        swapoff -a
        systemctl enable docker.service
        export KUBECONFIG=/etc/kubernetes/admin.conf
        echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> /etc/bash.bashrc
        # sudo -i
        # /vagrant/bin/594_kubeadm init
        # kubectl apply -f https://git.io/weave-kube-1.6
        # kubectl taint nodes --all node-role.kubernetes.io/master-
      SHELL
    end
  end
end

