# -*- coding: utf-8 -*-

class VagrantMachine
    """ represent a VagrantMachine creating from a VagrantMachineSet specification """

    attr_accessor :name
    attr_accessor :hostname
    attr_accessor :box
    attr_accessor :ip
    attr_accessor :cpus
    attr_accessor :memory
    attr_accessor :roles
    attr_accessor :sshKey
end

class Playground
    """ Class that bridges vagrant with kubeadm-playground.
        Vagrant should use the list of machines generated by kubeadm-playground """

    def self.machines
        machines = []

        tmp_folder = File.expand_path('../tmp', __dir__) 
        tmp_file = File.join tmp_folder, 'machines.yml'

        if File.exist?(tmp_file)
            data = YAML.load_file(tmp_file)

            data.each do |d|
                m = VagrantMachine.new
                m.name      = d['name']
                m.hostname  = d['hostname']
                m.box       = d['box']
                m.ip        = d['ip']
                m.cpus      = d['cpus']
                m.memory    = d['memory']
                m.roles     = d['roles']
                m.sshKey    = d['sshKey']
                machines << m
            end

            return machines
        else
            raise "\n\n  Playground not initialized yet. Use 'kubeadm-playground start' to create a new playground \n" 
        end
    end
end