---
- name: add docker dependencies for centos
  yum:
    name: "{{ item }}"
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: add docker yum repo
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable/
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true

- name: install docker
  yum:
    name: "{{ item }}"
    state: present
    allow_downgrade: True
  with_items:
    - "docker-ce-selinux-{{docker_redhat_version}}"

- name: start docker service
  service:
    name: docker
    enabled: true
    state: started
